proteins_fasta: Euphorbia_peplus.aa
token_score_bit_score_weight: 0.468
token_score_database_score_weight: 0.2098
token_score_overlap_score_weight: 0.3221
output: ahrd_output.csv
blast_dbs:
  swissprot:
    weight: 653
    description_score_bit_score_weight: 2.717061
    file: query_vs_SwissProt.tsv
    database: uniprot_sprot.fasta
    blacklist: AHRD/test/resources/blacklist_descline.txt
    filter: AHRD/test/resources/filter_descline_sprot.txt
    token_blacklist: AHRD/test/resources/blacklist_token.txt

  tair:
    weight: 854
    description_score_bit_score_weight: 2.917405
    file: query_vs_TAIR.tsv
    database: TAIR10_pep_20110103_representative_gene_model
    fasta_header_regex: "^>(?<accession>[aA][tT][0-9mMcC][gG]\\d+(\\.\\d+)?)\\s+\\|[^\\|]+\\|\\s+(?<description>[^\\|]+)(\\s*\\|.*)?$"
    short_accession_regex: "^(?<shortAccession>.+)$"
    blacklist: AHRD/test/resources/blacklist_descline.txt
    filter: AHRD/test/resources/filter_descline_tair.txt
    token_blacklist: AHRD/test/resources/blacklist_token.txt
